//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulstarCheck {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BulstarCheck.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави нов.
        /// </summary>
        internal static string application_add_button {
            get {
                return ResourceManager.GetString("application_add_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърдете.
        /// </summary>
        internal static string application_confirm {
            get {
                return ResourceManager.GetString("application_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Край.
        /// </summary>
        internal static string application_end {
            get {
                return ResourceManager.GetString("application_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход от програмата?.
        /// </summary>
        internal static string application_exit {
            get {
                return ResourceManager.GetString("application_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премахване на събитие?.
        /// </summary>
        internal static string event_confirm_delete {
            get {
                return ResourceManager.GetString("event_confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string event_date {
            get {
                return ResourceManager.GetString("event_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string event_desc {
            get {
                return ResourceManager.GetString("event_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма добавени 
        ///събития!.
        /// </summary>
        internal static string event_missing {
            get {
                return ResourceManager.GetString("event_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        internal static string event_name {
            get {
                return ResourceManager.GetString("event_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка при изпълнение:.
        /// </summary>
        internal static string exception {
            get {
                return ResourceManager.GetString("exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промяна на състоянието на лицето?.
        /// </summary>
        internal static string person_activate {
            get {
                return ResourceManager.GetString("person_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        internal static string person_fname {
            get {
                return ResourceManager.GetString("person_fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицето е в статус 
        ///&quot;Неактивен&quot;. Моля, 
        ///променете статуса 
        ///за разрешаване на 
        ///участие!.
        /// </summary>
        internal static string person_inactive {
            get {
                return ResourceManager.GetString("person_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        internal static string person_lname {
            get {
                return ResourceManager.GetString("person_lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЛПК.
        /// </summary>
        internal static string person_lpk {
            get {
                return ResourceManager.GetString("person_lpk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма данни за лицето. 
        ///Моля, добавете запис.
        /// </summary>
        internal static string person_missing {
            get {
                return ResourceManager.GetString("person_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Презиме.
        /// </summary>
        internal static string person_sname {
            get {
                return ResourceManager.GetString("person_sname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премахване на участник?.
        /// </summary>
        internal static string reg_confirm {
            get {
                return ResourceManager.GetString("reg_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидна дата.
        /// </summary>
        internal static string validation_event_date {
            get {
                return ResourceManager.GetString("validation_event_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание на събитие - непозволени символи.
        /// </summary>
        internal static string validation_event_desc {
            get {
                return ResourceManager.GetString("validation_event_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на събитие - непозволени символи.
        /// </summary>
        internal static string validation_event_name {
            get {
                return ResourceManager.GetString("validation_event_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Непозволени символи - име.
        /// </summary>
        internal static string validation_fname {
            get {
                return ResourceManager.GetString("validation_fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Непозволени символи - фамилия.
        /// </summary>
        internal static string validation_lname {
            get {
                return ResourceManager.GetString("validation_lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешно ЛПК.
        /// </summary>
        internal static string validation_lpk {
            get {
                return ResourceManager.GetString("validation_lpk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Непозволени символи - презиме.
        /// </summary>
        internal static string validation_sname {
            get {
                return ResourceManager.GetString("validation_sname", resourceCulture);
            }
        }
    }
}
